name: instagram_ultimate
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:


  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/readme/
    - assets/instagram_feed_page/icons/
    - assets/instagram_feed_page/posts/
    - assets/instagram_feed_page/profile_pictures/boys/
    - assets/instagram_feed_page/profile_pictures/girls/
    - assets/instagram_feed_page/profile_pictures/personal_profile/

  fonts:
    - family: instagramFont
      fonts:
        - asset: assets/fonts/instagramFont.otf

